baseurl      = "https://kkucherenkov.github.io/"
title        = "Kirill's homepage"
languageCode = "ru"
defaultContentLanguage = "ru"
theme        = "hello-friend-ng"

[pagination]
  pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A backend/mobile fullstack developer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage and blog"
  keywords = "homepage, blog, CV"

[taxonomies]
    tag = "tags"

[languages]
  [languages.ru]
    title = "Kirill's homepage"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 1
  [[menu.main]]
    identifier = "resume"
    name       = "CV"
    url        = "/resume"
    weight     = 2
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 3
